apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  serviceAccount: jenkins
  containers:
    - name: origin
      image: openshift/origin-cli
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug-v0.15.0
      imagePullPolicy: Always
      command:
        - /busybox/cat
      env:
        - name: PATH
          value: "$PATH:/busybox:/kaniko"
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      tty: true
      securityContext:
          privileged: true
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2048Mi"
    - name: ace
      image: ibmcom/ace
      command: 
        - "/bin/bash"
        - "-c"
      args: 
        - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2048Mi"
          cpu:  "2000m"
      env:
        - name: LICENSE
          value: "accept"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
        privileged: false
        capabilities:
          add:
          - SETPCAP
          - AUDIT_WRITE
          - CHOWN
          - NET_RAW
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETUID
          - SETGID
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - SETFCAP