apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  serviceAccountName: jenkinsci
  volumes:
    - name: docker-credentials
      projected:
        sources:
        - secret: 
            name: ibmcloud-cr
            items:
            - key: .dockerconfigjson
              path: config.json
  containers:
    - name: helm
      image: ibmcom/helm:v2.6.0
      imagePullPolicy: Always
      command:
        - cat
      tty: true
      resources:
          requests: 
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
    - name: buildah
      image: quay.io/buildah/stable
      imagePullPolicy: Always
      command:
      - cat
      tty: true
      volumeMounts:
      - name: docker-credentials
        mountPath: /home/jenkins/.docker
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2048Mi"
      securityContext:
          privileged: true
    - name: ace
      image: ibmcom/ace
      command: 
      - "/bin/bash"
      - "-c"
      args: 
      - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2048Mi"
          cpu:  "2000m"
      env:
      - name: LICENSE
        value: "accept"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
        privileged: false
        capabilities:
          add:
          - SETPCAP
          - AUDIT_WRITE
          - CHOWN
          - NET_RAW
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETUID
          - SETGID
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - SETFCAP