apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculadora-api.fullname" . }}
  labels:
{{ include "calculadora-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
      - name: {{ .name }}
        targetPort: {{ .name }}
        protocol: {{ .protocol }}
        port: {{ .port }}
    {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "calculadora-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
