apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-ephemeral
spec:
  serviceAccountName: jenkins
  volumes:
  - name: docker-credentials
    projected:
      sources:
      - secret:
        name: jenkins-dockercfg-lxlss
        items:
        - key: .dockercfg
          path: config.json
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.15.0
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-credentials
      mountPath: /kaniko/.docker
  - name: ace
    image: ibmcom/ace
    command: 
    - "/bin/bash"
    - "-c"
    args: 
    - cat
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu:  "2000m"
    env:
    - name: LICENSE
      value: "accept"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      privileged: false
      capabilities:
        add:
        - SETPCAP
        - AUDIT_WRITE
        - CHOWN
        - NET_RAW
        - DAC_OVERRIDE
        - FOWNER
        - FSETID
        - KILL
        - SETUID
        - SETGID
        - NET_BIND_SERVICE
        - SYS_CHROOT
        - SETFCAP