pipeline{
	agent {
		kubernetes{
			cloud "${cloudName}"
			label "backend-build"
			yamlFile "cicd/${buildPodFile}"
		}
  }
	parameters{
		string(name: "cloudName", description: "Cloud Name.")
		string(name: "buildPodFile", description: "Build Pod yaml file name.", defaultValue: "BuildPod.yaml")
		string(name: "imageRepository", description: "Container image repository")
		string(name: "kanikoFlags", description: "Additional flags for kaniko executor")
	}
	stages{
		stage('Prepare'){
			steps{
				script{
					tag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
				}
			}
		}
		stage('Build Bars'){
			steps{
				container('ace'){
					sh "bash -c 'mqsipackagebar -a compiled.bar -w . -k ApiCalculadora'"
				}
			}
   	}
		stage('Build Image'){
			environment{
				PATH="/busybox:/kaniko:$PATH"
				DESTINATION="${imageRepository}"
				TAG="${tag}"
			}
			steps{
				container('kaniko'){
					sh '''#!/busybox/sh
								echo "Building $DESTINATION"
								/kaniko/executor --dockerfile=Dockerfile --context="dir://`pwd`"  ${kanikoFlags} --destination="$DESTINATION:$TAG" --destination="$DESTINATION:latest"
						 '''
				}
			}
		}
		stage('Deploy Image'){
			environment{
				REPOSITORY="${imageRepository}"
				TAG="${tag}"
			}
			steps{
				container('helm'){
					sh '''#!/bin/sh
								/helm init --client-only
								/helm upgrade api charts/api --namespace default --install --set image.repository=$REPOSITORY,image.tag=$TAG
						 '''
				}
			}
		}
	}
}