pipeline{
	agent {
		kubernetes{
			cloud "${cloudName}"
			label "backend-build"
			yamlFile "cicd/${buildPodFile}"
		}
  }
	parameters{
		string(name: "cloudName", description: "Cloud Name.")
		string(name: "buildPodFile", description: "Build Pod yaml file name.")

	}
	stages{
		stage('Prepare'){
			steps{
				script{
					tag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
				}
			}
		}
		stage('Build Bars'){
			steps{
				container('ace'){
					sh "bash -c 'mqsipackagebar -a compiled.bar -w . -k ApiCalculadora'"
				}
			}
   	}
	}
}
