pipeline{
	agent {
		kubernetes{
			cloud "${cloudName}"
			label "backend-build"
			yamlFile "cicd/build-pods/${buildPodFile}"
		}
  }
	parameters{
		choice(
			choices: ['kubernetes','openshift'],
			description: 'Cloud Name',
			name: 'cloudName'
		)
		choice(
			choices: ['BuildPod-kaniko.yaml','BuildPod-buildah.yaml','BuildPod-docker.yaml'],
			description: 'Build Pod definition file.',
			name: 'buildPodFile',
			default: 'BuildPod-kaniko.yaml'
		)
		string(name: "imageRepository", description: "Container image repository")
		string(name: "kanikoFlags", description: "Additional flags for kaniko executor")
	}
	stages{
		stage('Prepare'){
			steps{
				script{
					tag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
				}
			}
		}
		stage('Build Bars'){
			steps{
				container('ace'){
					sh "bash -c 'mqsipackagebar -a compiled.bar -w . -k ApiCalculadora'"
				}
			}
   	}
		stage('Build Image'){
			environment{
				PATH="/busybox:/kaniko:$PATH"
				DESTINATION="${imageRepository}"
				TAG="${tag}"
			}
			steps{
				container('kaniko'){
					sh '''#!/busybox/sh
								echo "Building $DESTINATION"
								/kaniko/executor --dockerfile=Dockerfile --context="dir://`pwd`"  ${kanikoFlags} --destination="$DESTINATION:$TAG" --destination="$DESTINATION:latest"
						 '''
				}
			}
		}
		stage('Deploy Image'){
			environment{
				REPOSITORY="${imageRepository}"
				TAG="${tag}"
			}
			when{
				expression{params.cloudName == 'kubernetes'}
			}
			steps{
				container('helm'){
					sh '''#!/bin/sh
								/helm init --client-only
								/helm upgrade api charts/calculadora-api --namespace default --install --set image.repository=$REPOSITORY,image.tag=$TAG,service.type=NodePort
						 '''
				}
			}
		}
	}
}