kind: Template
apiVersion: v1
metadata:
  name: calculadora-api
  description: "Template to deploy Piloto #3 API"
  tags: ibmcom/ace
labels:
  template: calculadora-api
  template-version: '1.0'
  app: ${APP}-api
  component: api
parameters:
  - description: Application deployment name
    displayName: Application
    required: true
    name: APP
    value: 'calculadora'
  - description: 'The base name assigned to all of the objects defined in this template.'
    displayName: Name
    required: true
    name: NAME
    value: api
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: piloto3
  - description: The ImageStream name
    displayName: ImageStream
    name: IMAGE
    required: true
    value: api
  - description: Service Account with ibm-anyuid-scc configured
    displayName: Service Account 
    name: SA
    required: true
    value: default
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}-prod
      labels:
        version: prod
    spec:
      replicas: 1
      selector:
        app: ${APP}-api
      template:
        metadata:
          labels:
            app: ${APP}-api
            version: prod
          annotations:
            sidecar.istio.io/inject: "true"
        spec:
          serviceAccount: ${SA}
          volumes:
            - name: ace-policies
              emptyDir: {}
            - name: ace-setdbparms
              emptyDir: {}
          initContainers:
            - name: prepare-configs
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-db
                      key: password
                - name: DB_SERVICE_NAME
                  value: ${APP}-db
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: ${APP}-db
                      key: dbname
              image: " "
              imagePullPolicy: "Always"
              volumeMounts:
                - name: ace-policies
                  mountPath: /policy
                - name: ace-setdbparms
                  mountPath: /setdbparms
              
          containers:
            - name: ace
              env:
                - name: LICENSE 
                  value: accept
              image: " "
              imagePullPolicy: "Always"
              ports:
                - containerPort: 7600
                  protocol: TCP
                - containerPort: 7800
                  protocol: TCP
                - containerPort: 7843
                  protocol: TCP
                - containerPort: 9483
                  protocol: TCP
              livenessProbe:
                exec:
                  command:
                  - chkacehealthy
              readinessProbe:
                exec:
                  command:
                  - chkaceready
              volumeMounts:
                - name: ace-policies
                  mountPath: /home/aceuser/initial-config/policy
                - name: ace-setdbparms
                  mountPath: /home/aceuser/initial-config/setdbparms
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 1000
                privileged: false
                capabilities:
                  add:
                  - SETPCAP
                  - AUDIT_WRITE
                  - CHOWN
                  - NET_RAW
                  - DAC_OVERRIDE
                  - FOWNER
                  - FSETID
                  - KILL
                  - SETUID
                  - SETGID
                  - NET_BIND_SERVICE
                  - SYS_CHROOT
                  - SETFCAP
      triggers:
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - ace
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}:latest
              namespace: ${NAMESPACE}
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - prepare-configs
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}-init:latest
              namespace: ${NAMESPACE}
        - type: ConfigChange
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}-canary
      labels:
        version: canary
    spec:
      replicas: 1
      selector:
        app: ${APP}-api
      template:
        metadata:
          labels:
            app: ${APP}-api
            version: canary
          annotations:
            sidecar.istio.io/inject: "true"
        spec:
          serviceAccount: ${SA}
          volumes:
            - name: ace-policies
              emptyDir: {}
            - name: ace-setdbparms
              emptyDir: {}
          initContainers:
            - name: prepare-configs
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-db
                      key: password
                - name: DB_SERVICE_NAME
                  value: ${APP}-db
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: ${APP}-db
                      key: dbname
              image: " "
              imagePullPolicy: "Always"
              volumeMounts:
                - name: ace-policies
                  mountPath: /policy
                - name: ace-setdbparms
                  mountPath: /setdbparms
              
          containers:
            - name: ace
              env:
                - name: LICENSE 
                  value: accept
              image: " "
              imagePullPolicy: "Always"
              ports:
                - containerPort: 7600
                  protocol: TCP
                - containerPort: 7800
                  protocol: TCP
                - containerPort: 7843
                  protocol: TCP
                - containerPort: 9483
                  protocol: TCP
              livenessProbe:
                exec:
                  command:
                  - chkacehealthy
              readinessProbe:
                exec:
                  command:
                  - chkaceready
              volumeMounts:
                - name: ace-policies
                  mountPath: /home/aceuser/initial-config/policy
                - name: ace-setdbparms
                  mountPath: /home/aceuser/initial-config/setdbparms
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 1000
                privileged: false
                capabilities:
                  add:
                  - SETPCAP
                  - AUDIT_WRITE
                  - CHOWN
                  - NET_RAW
                  - DAC_OVERRIDE
                  - FOWNER
                  - FSETID
                  - KILL
                  - SETUID
                  - SETGID
                  - NET_BIND_SERVICE
                  - SYS_CHROOT
                  - SETFCAP
      triggers:
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - ace
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}:canary
              namespace: ${NAMESPACE}
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - prepare-configs
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}-init:canary
              namespace: ${NAMESPACE}
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    labels:
      app: ${APP}-api
    spec:
      selector:
        app: ${APP}-api
      type: ClusterIP
      ports:
        - port: 7600
          protocol: TCP
          name: http-7600
        - port: 7800
          protocol: TCP
          name: http-7800
        - port: 7843
          protocol: TCP
          name: https-7843
        - port: 9843
          protocol: TCP
          name: tcp-9843
  - kind: VirtualService
    apiVersion: networking.istio.io/v1alpha3
    metadata:
      name: ${APP}-${NAME}
    spec:
      hosts:
        - ${APP}-${NAME}
      http:
        - match:
            - uri: 
                prefix: /
          route:
            - destination:
                host: ${APP}-${NAME}
                subset: prod
                port:
                  number: 7800
              weight: 100
            - destination:
                host: ${APP}-${NAME}
                subset: canary
                port:
                  number: 7800
              weight: 0
  - kind: DestinationRule
    apiVersion: networking.istio.io/v1alpha3
    metadata:
      name: ${APP}-${NAME}
    spec:
      host: ${APP}-${NAME}
      subsets:
      - name: prod
        labels:
          version: prod
      - name: canary
        labels:
          version: canary